# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

curr = 1
succ = 2
limit = 31
fibo_seq = [1] 

limit.times do |i|
  curr, succ = succ, curr + succ
  fibo_seq << curr
end

answer = []
sum = 0

fibo_seq.each do |el|
  answer << el if el % 2 == 0 
end

answer.each { |el| sum += el}
p sum # 4613732